// VieNeu-TTS: app-managed local Vietnamese TTS with voice cloning.
//
// Layout (mirrors the FaceFusion managed install):
//   app_data/vieneu/.venv/        ← Python env with the `vieneu` package
//   app_data/vieneu/worker.py     ← JSON-lines synthesis worker (long-lived)
//   app_data/vieneu/warmup.py     ← one-shot model download + smoke test
//   app_data/vieneu/.hf/          ← HuggingFace cache (kept inside the dir so
//                                    uninstall reclaims the models too)
//   app_data/vieneu/voices/       ← cloned voice profiles (wav + profiles.json)
//   app_data/vieneu/.installed    ← marker: install + warmup completed
//
// Synthesis runs through a persistent stdin/stdout worker so the model loads
// once per session instead of once per subtitle line. The worker owns the real
// stdout for its JSON protocol and redirects library prints to stderr.
use crate::services::uv;
use crate::utils::CommandExt;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::LazyLock;
use tauri::{AppHandle, Manager};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader, Lines};
use tokio::process::{Child, ChildStdin, ChildStdout, Command};
use tokio::sync::Mutex;

const SETUP_EVENT: &str = "vieneu-setup";
const PYTHON_VERSION: &str = "3.12";
/// Pinned so every machine installs the same engine. Bumping this is a
/// deliberate upgrade; the Voices page also offers an in-place update to
/// whatever PyPI currently publishes.
const VIENEU_VERSION: &str = "3.2.4";
/// First worker start may re-download models if the cache was cleared.
const READY_TIMEOUT_SECS: u64 = 1800;
/// One line of speech on CPU is seconds; leave headroom for slow machines.
const REQUEST_TIMEOUT_SECS: u64 = 600;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTtsStatus {
    pub installed: bool,
    pub dir: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VoiceProfile {
    pub id: String,
    pub name: String,
    /// Absolute path of the reference wav used for cloning.
    pub file: String,
    pub created_at: String,
    /// Shipped with the app (seeded from BUNDLED_VOICES). The UI lists these
    /// under "built-in voices" and offers no delete button.
    #[serde(default)]
    pub builtin: bool,
    /// VieNeu reading style: "tu_nhien" (default) | "tin_tuc" | "doc_truyen".
    /// Matching the style to how the reference was recorded measurably
    /// improves speaker similarity.
    #[serde(default)]
    pub style: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresetVoice {
    /// Bare voice name accepted by infer(voice=...), e.g. "Minh Đức".
    pub id: String,
    /// Display label from the SDK, e.g. "Minh Đức — Nam · Bắc · Tin tức".
    pub label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTtsVoices {
    /// Built-in preset voices reported by the VieNeu SDK.
    pub presets: Vec<PresetVoice>,
    /// User-cloned voice profiles.
    pub profiles: Vec<VoiceProfile>,
    /// Fine-tuned LoRA voices (highest fidelity, slower engine).
    #[serde(default)]
    pub loras: Vec<PresetVoice>,
}

/// Voices served by the worker's second (torch) engine — ids must match
/// WORKER_PY's STANDARD_VOICES.
///
/// Empty on purpose: that engine is VieNeu's older 0.3B architecture and only
/// outputs 24kHz, so its audio is audibly duller than the 48kHz v3 Turbo path
/// despite using the author's own Ngọc Huyền reference codes. The LoRA adapter
/// that would have justified it is unusable (trained against a base revision
/// the author replaced; the old revision reads the reference sentence aloud).
/// The worker code stays so re-enabling is a one-line change if upstream ships
/// a v3-compatible fine-tune.
const LORA_VOICE_LIST: &[(&str, &str)] = &[];

fn managed_dir(app: &AppHandle) -> Option<PathBuf> {
    app.path().app_data_dir().ok().map(|p| p.join("vieneu"))
}

fn venv_python(dir: &Path) -> PathBuf {
    if cfg!(windows) {
        dir.join(".venv").join("Scripts").join("python.exe")
    } else {
        dir.join(".venv").join("bin").join("python")
    }
}

fn voices_dir(dir: &Path) -> PathBuf {
    dir.join("voices")
}

fn profiles_path(dir: &Path) -> PathBuf {
    voices_dir(dir).join("profiles.json")
}

fn emit_setup(app: &AppHandle, stage: &str, percent: i32, message: &str) {
    uv::emit_setup(app, SETUP_EVENT, stage, percent, message);
}

// ── embedded Python sources ────────────────────────────────────────────────

const WORKER_PY: &str = r#"# Auto-generated by Youwee. JSON-lines worker for VieNeu local TTS.
import json
import os
import sys

# The vieneu library (and its deps) may print to stdout; the JSON protocol
# must own the real stdout, so keep a private handle and route prints to stderr.
proto = os.fdopen(os.dup(1), "w", buffering=1)
sys.stdout = sys.stderr


def preset_entry(v):
    # list_preset_voices() entries vary by SDK version: plain names, dicts, or
    # (display label, voice name) tuples. Normalize to {id, label} where id is
    # what infer(voice=...) accepts.
    if isinstance(v, (list, tuple)) and v:
        return {"id": str(v[-1]), "label": str(v[0]) or str(v[-1])}
    if isinstance(v, dict):
        name = str(v.get("name") or v.get("id") or v)
        return {"id": name, "label": str(v.get("label") or name)}
    s = str(v)
    return {"id": s, "label": s}


# High-fidelity voices served by the "standard" (torch) engine, keyed by id.
#
# `codes_repo` supplies the reference codes+text (published in a voices.json);
# for Ngọc Huyền those live in the author's LoRA repo. The LoRA ADAPTER itself
# is deliberately NOT loaded: it was trained against a base revision the author
# has since replaced, and pinning that dead revision produces broken audio —
# the model reads the reference sentence aloud and rambles for 15-25s. Using
# the current base with these reference codes is both correct and fast
# (~3s of audio in ~4s), and still reproduces the target voice.
STANDARD_VOICES = {
    "ngoc-huyen": {
        "base": "pnnbao-ump/VieNeu-TTS-0.3B",
        "codes_repo": "pnnbao-ump/VieNeu-TTS-0.3B-lora-ngoc-huyen",
        "preset": "NgocHuyen",
    }
}


def standard_synthesize(std, voice_id, text, out):
    cfg = STANDARD_VOICES[voice_id]
    if std["engine"] is None:
        # This engine's model is NOT fetched during install, so it needs the
        # Hub on first use — lift the worker's offline default just for it.
        os.environ.pop("HF_HUB_OFFLINE", None)
        from vieneu import Vieneu

        device = "cpu"
        try:
            import torch

            if torch.backends.mps.is_available():
                device = "mps"
            elif torch.cuda.is_available():
                device = "cuda"
        except Exception:
            pass
        std["engine"] = Vieneu(
            mode="standard",
            backbone_repo=cfg["base"],
            gguf_filename=None,
            backbone_device=device,
            codec_device="cpu",
        )
    voice = std["voices"].get(voice_id)
    if voice is None:
        import json as _json

        from huggingface_hub import hf_hub_download

        preset = _json.load(open(hf_hub_download(cfg["codes_repo"], "voices.json")))["presets"][
            cfg["preset"]
        ]
        try:
            import torch

            codes = torch.tensor(preset["codes"], dtype=torch.long)
        except ImportError:
            import numpy as np

            codes = np.array(preset["codes"], dtype=np.int64)
        voice = {"codes": codes, "text": preset["text"]}
        std["voices"][voice_id] = voice
    audio = std["engine"].infer(text, voice=voice)
    std["engine"].save(audio, out)


def main():
    from vieneu import Vieneu

    # Engine precision comes from engine.json (written by the app): "int8" is
    # the fast default, "fp32" trades ~15% speed for noticeably closer voice
    # reproduction. Both are the same 48kHz v3 Turbo model.
    precision = "int8"
    try:
        with open("engine.json", encoding="utf-8") as fh:
            precision = (json.load(fh).get("precision") or "int8").lower()
    except Exception:
        pass
    if precision not in ("int8", "fp32"):
        precision = "int8"

    tts = Vieneu(precision=precision)
    # Lazy second engine for the high-fidelity voices; not loaded until asked.
    std = {"engine": None, "voices": {}}
    # Reference voices registered this session: (path, mtime) -> internal name.
    # add_voice() encodes the reference ONCE (the slow part, several seconds);
    # every later synthesis with that voice then runs at preset speed instead
    # of re-encoding the reference audio on every single request.
    registered = {}
    proto.write(json.dumps({"event": "ready"}) + "\n")
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        rid = None
        try:
            req = json.loads(line)
            rid = req.get("id")
            op = req.get("op")
            if op == "voices":
                try:
                    voices = [preset_entry(v) for v in (tts.list_preset_voices() or [])]
                except Exception:
                    voices = []
                proto.write(
                    json.dumps({"id": rid, "ok": True, "voices": voices}, ensure_ascii=False) + "\n"
                )
            elif op == "tts" and req.get("lora"):
                voice_id = req["lora"]
                if voice_id not in STANDARD_VOICES:
                    proto.write(json.dumps({"id": rid, "ok": False, "error": "unknown hq voice"}) + "\n")
                    continue
                standard_synthesize(std, voice_id, req["text"], req["out"])
                proto.write(
                    json.dumps({"id": rid, "ok": True, "path": req["out"]}, ensure_ascii=False) + "\n"
                )
            elif op == "tts":
                kwargs = {}
                if req.get("ref_audio"):
                    ref = req["ref_audio"]
                    denoise = bool(req.get("denoise", True))
                    try:
                        key = (ref, os.path.getmtime(ref))
                    except OSError:
                        key = (ref, 0)
                    style = req.get("style") or "tu_nhien"
                    name = registered.get(key)
                    if name is None:
                        try:
                            name = "__ref_%d" % len(registered)
                            tts.add_voice(name, ref, denoise=denoise, style=style)
                            registered[key] = name
                        except Exception:
                            name = None
                    if name is not None:
                        kwargs["voice"] = name
                    else:
                        # Registration failed — fall back to the per-request path.
                        kwargs["ref_audio"] = ref
                        kwargs["denoise"] = denoise
                    kwargs["style"] = style
                elif req.get("voice"):
                    kwargs["voice"] = req["voice"]
                # VieNeu stamps an inaudible watermark by default; skipping it
                # measurably improves speaker similarity and this audio never
                # leaves the user's machine unattributed.
                kwargs["apply_watermark"] = False
                audio = tts.infer(req["text"], **kwargs)
                tts.save(audio, req["out"])
                proto.write(
                    json.dumps({"id": rid, "ok": True, "path": req["out"]}, ensure_ascii=False) + "\n"
                )
            elif op == "ping":
                proto.write(json.dumps({"id": rid, "ok": True}) + "\n")
            else:
                proto.write(json.dumps({"id": rid, "ok": False, "error": "unknown op"}) + "\n")
        except Exception as exc:  # keep serving after a bad request
            import traceback

            traceback.print_exc()
            proto.write(
                json.dumps({"id": rid, "ok": False, "error": str(exc)}, ensure_ascii=False) + "\n"
            )


if __name__ == "__main__":
    main()
"#;

const WARMUP_PY: &str = r#"# Auto-generated by Youwee. Downloads VieNeu models and runs one synthesis.
import sys

from vieneu import Vieneu


def voice_id(v):
    # Entries may be names, dicts, or (display label, voice name) tuples;
    # infer(voice=...) wants the bare name.
    if isinstance(v, (list, tuple)) and v:
        return str(v[-1])
    if isinstance(v, dict):
        return str(v.get("name") or v.get("id") or v)
    return str(v)


tts = Vieneu()
kwargs = {}
try:
    voices = [voice_id(v) for v in (tts.list_preset_voices() or [])]
    if voices:
        kwargs["voice"] = voices[0]
except Exception:
    pass
audio = tts.infer("Xin chào, đây là bản kiểm tra giọng đọc.", **kwargs)
tts.save(audio, sys.argv[1])
print("WARMUP_OK")
"#;

// ── status / install / uninstall ───────────────────────────────────────────

pub async fn check_vieneu_internal(app: &AppHandle) -> LocalTtsStatus {
    let Some(dir) = managed_dir(app) else {
        return LocalTtsStatus {
            installed: false,
            dir: None,
            error: Some("Failed to resolve app data dir".to_string()),
        };
    };
    let installed = venv_python(&dir).exists()
        && dir.join("worker.py").exists()
        && dir.join(".installed").exists();
    LocalTtsStatus {
        installed,
        dir: Some(dir.to_string_lossy().to_string()),
        error: None,
    }
}

/// Stream a python script's output as setup progress under `stage`.
async fn run_python_step(
    app: &AppHandle,
    python: &Path,
    args: &[&str],
    dir: &Path,
    stage: &str,
) -> Result<(), String> {
    let mut cmd = Command::new(python);
    cmd.arg("-u")
        .args(args)
        .current_dir(dir)
        .env("HF_HOME", dir.join(".hf"))
        .env("HF_HUB_DISABLE_TELEMETRY", "1")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        // Dropped future (cancelled install) must not leave python running.
        .kill_on_drop(true);
    cmd.hide_window();

    let mut child = cmd
        .spawn()
        .map_err(|e| format!("Failed to start python: {}", e))?;
    let stdout = child.stdout.take().ok_or("no stdout")?;
    let stderr = child.stderr.take().ok_or("no stderr")?;

    // HF downloads write tqdm bars to stderr with \r; split on both so the
    // panel shows moving progress instead of one endless line.
    async fn pump<R: tokio::io::AsyncRead + Unpin>(
        mut reader: R,
        app: AppHandle,
        stage: String,
    ) -> String {
        use tokio::io::AsyncReadExt;
        let mut buf = [0u8; 4096];
        let mut pending = String::new();
        let mut tail = String::new();
        let mut last = String::new();
        loop {
            let n = match reader.read(&mut buf).await {
                Ok(0) | Err(_) => break,
                Ok(n) => n,
            };
            pending.push_str(&String::from_utf8_lossy(&buf[..n]));
            while let Some(pos) = pending.find(['\r', '\n']) {
                let seg: String = pending.drain(..=pos).collect();
                let seg = seg.trim_end_matches(['\r', '\n']).trim().to_string();
                if seg.is_empty() || seg == last {
                    continue;
                }
                last = seg.clone();
                emit_setup(&app, &stage, -1, &seg);
                if tail.len() > 4000 {
                    tail.drain(..2000);
                }
                tail.push_str(&seg);
                tail.push('\n');
            }
        }
        tail
    }

    let t_out = tokio::spawn(pump(stdout, app.clone(), stage.to_string()));
    let t_err = tokio::spawn(pump(stderr, app.clone(), stage.to_string()));

    let status = child
        .wait()
        .await
        .map_err(|e| format!("python process error: {}", e))?;
    let out = t_out.await.unwrap_or_default();
    let err = t_err.await.unwrap_or_default();

    if status.success() {
        Ok(())
    } else {
        let combined = format!("{}\n{}", out, err);
        let tail = combined
            .lines()
            .filter(|l| !l.trim().is_empty())
            .rev()
            .take(6)
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .collect::<Vec<_>>()
            .join("\n");
        Err(format!("python step failed:\n{}", tail))
    }
}

/// Remove the Gradio web-UI stack (~200MB): `vieneu` declares it as a hard
/// dependency but only imports it from its own `vieneu-web` command, which
/// this app never runs. Must be re-run after every install AND every upgrade,
/// since pip pulls the declared dependencies back each time. scikit-learn is
/// deliberately kept — librosa needs it. Best-effort: a future dependency
/// graph may not contain some of these names.
async fn trim_unused_packages(app: &AppHandle, uv_bin: &Path, dir: &Path, python_arg: &str) {
    emit_setup(app, "deps", -1, "Removing unused UI packages…");
    let _ = uv::run_uv_step(
        app,
        uv_bin,
        &[
            "pip",
            "uninstall",
            "--python",
            python_arg,
            "gradio",
            "hf-gradio",
            "gradio-client",
            "pandas",
            "pillow",
            "orjson",
            "fastapi",
            "starlette",
            "uvicorn",
            "safehttpx",
            "groovy",
            "ffmpy",
            "pydub",
        ],
        dir,
        SETUP_EVENT,
        "deps",
    )
    .await;
}

/// Install a self-contained VieNeu env with uv, then warm it up so the model
/// weights download now (with a progress UI) rather than on the first dub.
pub async fn install_vieneu_internal(app: &AppHandle) -> Result<LocalTtsStatus, String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    tokio::fs::create_dir_all(&dir)
        .await
        .map_err(|e| format!("Failed to create vieneu dir: {}", e))?;

    let uv_bin = uv::ensure_uv(app, SETUP_EVENT).await?;

    emit_setup(app, "python", -1, &format!("Preparing Python {}…", PYTHON_VERSION));
    // --clear: a retry after a failed install leaves a stale .venv behind, and
    // uv refuses to reuse it ("A virtual environment already exists").
    uv::run_uv_step(
        app,
        &uv_bin,
        &["venv", "--clear", "--python", PYTHON_VERSION, ".venv"],
        &dir,
        SETUP_EVENT,
        "python",
    )
    .await?;

    emit_setup(app, "deps", -1, "Installing VieNeu-TTS (this can take a while)…");
    // Constraints keep the resolver on modern wheels: unconstrained, it pairs
    // the newest numpy with librosa's numba dependency by backtracking numba
    // all the way to 0.53 (llvmlite 0.36), which only builds on Python <3.10
    // and fails the whole install. numba >=0.59 has cp312 wheels and pulls a
    // numpy it actually supports. Written next to the venv and passed by its
    // RELATIVE name: uv mis-parses flag paths containing spaces, and the
    // macOS app_data path ("Application Support") always has one.
    const CONSTRAINTS_FILE: &str = "youwee_constraints.txt";
    tokio::fs::write(dir.join(CONSTRAINTS_FILE), "numba>=0.59\nllvmlite>=0.42\n")
        .await
        .map_err(|e| format!("Failed to write constraints: {}", e))?;
    let python_arg = venv_python(&dir).to_string_lossy().to_string();
    let vieneu_spec = format!("vieneu=={}", VIENEU_VERSION);
    // torch/torchaudio ride along even though preset synthesis is pure ONNX:
    // voice cloning (encoding the reference audio) imports torch, and without
    // it every cloned-voice synthesis dies with "No module named 'torch'".
    // On macOS this also unlocks MPS acceleration.
    uv::run_uv_step(
        app,
        &uv_bin,
        &[
            "pip",
            "install",
            "--python",
            &python_arg,
            "--constraint",
            CONSTRAINTS_FILE,
            &vieneu_spec,
            "torch",
            "torchaudio",
            // For LoRA fine-tuned voices (standard engine + PEFT adapters).
            "transformers",
            "peft",
        ],
        &dir,
        SETUP_EVENT,
        "deps",
    )
    .await?;

    trim_unused_packages(app, &uv_bin, &dir, &python_arg).await;

    tokio::fs::write(dir.join("worker.py"), WORKER_PY)
        .await
        .map_err(|e| format!("Failed to write worker: {}", e))?;
    tokio::fs::write(dir.join("warmup.py"), WARMUP_PY)
        .await
        .map_err(|e| format!("Failed to write warmup: {}", e))?;

    emit_setup(app, "models", -1, "Downloading voice models (one time)…");
    let warmup_out = dir.join("warmup.wav");
    let warmup_out_str = warmup_out.to_string_lossy().to_string();
    run_python_step(
        app,
        &venv_python(&dir),
        &["warmup.py", &warmup_out_str],
        &dir,
        "models",
    )
    .await?;
    let _ = tokio::fs::remove_file(&warmup_out).await;

    tokio::fs::write(dir.join(".installed"), "ok")
        .await
        .map_err(|e| format!("Failed to write install marker: {}", e))?;

    seed_bundled_voices(&dir).await;

    emit_setup(app, "done", 100, "Local TTS is ready.");
    Ok(check_vieneu_internal(app).await)
}

// ── version + in-place update ──────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTtsVersion {
    /// Version actually installed in the venv (None when not installed).
    pub installed: Option<String>,
    /// Version this app build pins for fresh installs.
    pub pinned: String,
    /// Newest version on PyPI (None when the check failed or wasn't run).
    pub latest: Option<String>,
    /// True when `latest` is present and differs from `installed`.
    pub update_available: bool,
}

/// Read the version of the `vieneu` package inside the managed venv.
async fn installed_vieneu_version(app: &AppHandle) -> Option<String> {
    let dir = managed_dir(app)?;
    let python = venv_python(&dir);
    if !python.exists() {
        return None;
    }
    let mut cmd = Command::new(&python);
    cmd.arg("-c")
        .arg("import importlib.metadata as m; print(m.version('vieneu'))")
        .current_dir(&dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::null());
    cmd.hide_window();
    let out = cmd.output().await.ok()?;
    if !out.status.success() {
        return None;
    }
    let v = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!v.is_empty()).then_some(v)
}

/// Version info; queries PyPI only when `check_remote` is set (the UI does
/// that behind an explicit button so opening the page stays offline).
pub async fn vieneu_version_internal(app: &AppHandle, check_remote: bool) -> LocalTtsVersion {
    let installed = installed_vieneu_version(app).await;
    let mut latest = None;
    if check_remote {
        latest = fetch_latest_vieneu_version().await;
    }
    let update_available = match (&installed, &latest) {
        (Some(i), Some(l)) => i != l,
        _ => false,
    };
    LocalTtsVersion {
        installed,
        pinned: VIENEU_VERSION.to_string(),
        latest,
        update_available,
    }
}

async fn fetch_latest_vieneu_version() -> Option<String> {
    let client = reqwest::Client::builder()
        .user_agent("Youwee")
        .timeout(std::time::Duration::from_secs(20))
        .build()
        .ok()?;
    let resp = client
        .get("https://pypi.org/pypi/vieneu/json")
        .send()
        .await
        .ok()?;
    if !resp.status().is_success() {
        return None;
    }
    let json: serde_json::Value = resp.json().await.ok()?;
    json.get("info")?
        .get("version")?
        .as_str()
        .map(String::from)
}

/// Upgrade the `vieneu` package in place, keeping the venv, model cache and
/// cloned voices. `version` may pin a specific release; None takes the newest.
pub async fn update_vieneu_internal(
    app: &AppHandle,
    version: Option<String>,
) -> Result<LocalTtsVersion, String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    if !dir.join(".installed").exists() {
        return Err("Local TTS is not installed".to_string());
    }
    // The running worker holds the old package loaded; stop it so the next
    // request starts on the new one.
    shutdown_worker().await;

    let uv_bin = uv::ensure_uv(app, SETUP_EVENT).await?;
    let python_arg = venv_python(&dir).to_string_lossy().to_string();
    let spec = match &version {
        Some(v) => format!("vieneu=={}", v),
        None => "vieneu".to_string(),
    };

    emit_setup(app, "deps", -1, "Updating VieNeu-TTS…");
    // Constraints still apply: without them the resolver can drag numba back
    // to a release that cannot build on Python 3.12.
    tokio::fs::write(
        dir.join("youwee_constraints.txt"),
        "numba>=0.59\nllvmlite>=0.42\n",
    )
    .await
    .map_err(|e| format!("Failed to write constraints: {}", e))?;
    uv::run_uv_step(
        app,
        &uv_bin,
        &[
            "pip",
            "install",
            "--upgrade",
            "--python",
            &python_arg,
            "--constraint",
            "youwee_constraints.txt",
            &spec,
        ],
        &dir,
        SETUP_EVENT,
        "deps",
    )
    .await?;

    // The upgrade re-installs vieneu's declared deps, so trim again.
    trim_unused_packages(app, &uv_bin, &dir, &python_arg).await;

    // A new release may ship a different preset line-up; re-read it once.
    let _ = tokio::fs::remove_file(presets_cache_path(&dir)).await;

    // Ship any worker-protocol changes that came with the app update too.
    let _ = tokio::fs::write(dir.join("worker.py"), WORKER_PY).await;

    emit_setup(app, "done", 100, "Update complete.");
    Ok(vieneu_version_internal(app, false).await)
}

pub async fn uninstall_vieneu_internal(app: &AppHandle) -> Result<(), String> {
    shutdown_worker().await;
    if let Some(dir) = managed_dir(app) {
        if dir.exists() {
            tokio::fs::remove_dir_all(&dir)
                .await
                .map_err(|e| format!("Failed to remove install: {}", e))?;
        }
    }
    Ok(())
}

// ── persistent synthesis worker ────────────────────────────────────────────

struct Worker {
    child: Child,
    stdin: ChildStdin,
    lines: Lines<BufReader<ChildStdout>>,
    next_id: u64,
}

static WORKER: LazyLock<Mutex<Option<Worker>>> = LazyLock::new(|| Mutex::new(None));

async fn spawn_worker(app: &AppHandle) -> Result<Worker, String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    let python = venv_python(&dir);
    if !python.exists() || !dir.join(".installed").exists() {
        return Err("Local TTS is not installed".to_string());
    }
    // Rewrite the worker on every spawn so an app update ships protocol fixes
    // without requiring a reinstall.
    tokio::fs::write(dir.join("worker.py"), WORKER_PY)
        .await
        .map_err(|e| format!("Failed to write worker: {}", e))?;

    let mut cmd = Command::new(&python);
    cmd.arg("-u")
        .arg("worker.py")
        .current_dir(&dir)
        .env("HF_HOME", dir.join(".hf"))
        .env("HF_HUB_DISABLE_TELEMETRY", "1")
        // Models are downloaded during install, so serving needs no network.
        // Offline mode skips a per-start Hub round-trip (worker boot drops
        // from ~7s to ~3s) and silences the "unauthenticated requests" notice.
        .env("HF_HUB_OFFLINE", "1")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true);
    cmd.hide_window();

    let mut child = cmd
        .spawn()
        .map_err(|e| format!("Failed to start TTS worker: {}", e))?;
    let stdin = child.stdin.take().ok_or("no stdin")?;
    let stdout = child.stdout.take().ok_or("no stdout")?;
    let stderr = child.stderr.take().ok_or("no stderr")?;

    // Drain stderr (library logs, tracebacks) so the pipe never fills up and
    // blocks the worker. Log lines in debug builds for diagnosability.
    tokio::spawn(async move {
        let mut lines = BufReader::new(stderr).lines();
        while let Ok(Some(_line)) = lines.next_line().await {
            #[cfg(debug_assertions)]
            println!("[VIENEU] {}", _line);
        }
    });

    let mut lines = BufReader::new(stdout).lines();

    // Wait for the ready handshake — the model loads (or re-downloads) here.
    let ready = tokio::time::timeout(
        std::time::Duration::from_secs(READY_TIMEOUT_SECS),
        async {
            while let Ok(Some(line)) = lines.next_line().await {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(&line) {
                    if v.get("event").and_then(|e| e.as_str()) == Some("ready") {
                        return true;
                    }
                }
            }
            false
        },
    )
    .await;

    match ready {
        Ok(true) => Ok(Worker {
            child,
            stdin,
            lines,
            next_id: 1,
        }),
        Ok(false) => {
            let _ = child.kill().await;
            Err("TTS worker exited before becoming ready".to_string())
        }
        Err(_) => {
            let _ = child.kill().await;
            Err("TTS worker timed out while loading the model".to_string())
        }
    }
}

/// Send one JSON request to the worker and await its matching response.
/// The worker slot's mutex serializes callers, which is the right shape for
/// local inference anyway (one synthesis saturates the CPU/GPU).
async fn worker_request(
    app: &AppHandle,
    mut payload: serde_json::Value,
    timeout_secs: u64,
) -> Result<serde_json::Value, String> {
    let mut slot = WORKER.lock().await;

    let alive = slot
        .as_mut()
        .map(|w| w.child.try_wait().ok().flatten().is_none())
        .unwrap_or(false);
    if !alive {
        *slot = Some(spawn_worker(app).await?);
    }
    let worker = slot.as_mut().expect("worker just ensured");

    let id = worker.next_id;
    worker.next_id += 1;
    payload["id"] = serde_json::json!(id);
    let line = format!("{}\n", payload);

    let result = tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), async {
        worker
            .stdin
            .write_all(line.as_bytes())
            .await
            .map_err(|e| format!("TTS worker write failed: {}", e))?;
        loop {
            match worker.lines.next_line().await {
                Ok(Some(line)) => {
                    let Ok(v) = serde_json::from_str::<serde_json::Value>(&line) else {
                        continue;
                    };
                    if v.get("id").and_then(|i| i.as_u64()) == Some(id) {
                        return Ok(v);
                    }
                }
                Ok(None) => return Err("TTS worker closed unexpectedly".to_string()),
                Err(e) => return Err(format!("TTS worker read failed: {}", e)),
            }
        }
    })
    .await
    .unwrap_or_else(|_| Err("TTS worker request timed out".to_string()));

    // A dead/hung worker never recovers on its own — drop it so the next
    // request starts fresh.
    if result.is_err() {
        if let Some(mut w) = slot.take() {
            let _ = w.child.kill().await;
        }
    }
    result
}

/// Start the synthesis worker if it isn't running yet, without asking it for
/// anything. The Voices page calls this on open so the model is already in
/// memory by the time the user hits a preview button (loading it lazily made
/// the first click feel broken — several seconds before any sound).
pub async fn warm_worker(app: &AppHandle) -> Result<(), String> {
    let mut slot = WORKER.lock().await;
    let alive = slot
        .as_mut()
        .map(|w| w.child.try_wait().ok().flatten().is_none())
        .unwrap_or(false);
    if alive {
        return Ok(());
    }
    *slot = Some(spawn_worker(app).await?);
    Ok(())
}

/// Stop the worker if running (uninstall, app-driven resets).
pub async fn shutdown_worker() {
    let mut slot = WORKER.lock().await;
    if let Some(mut w) = slot.take() {
        let _ = w.child.kill().await;
    }
}

// ── synthesis + voices API ─────────────────────────────────────────────────

/// Where cached voice samples live. The preview sentence is fixed, so a
/// voice's sample is identical forever — keeping it on disk means the very
/// first preview after an app start plays instantly instead of paying for a
/// synthesis. Invalidated by voice deletion, engine upgrades and precision
/// changes (see clear_sample_cache).
fn samples_dir(dir: &Path) -> PathBuf {
    dir.join("samples")
}

/// Path a given voice+text pair caches to. The text is hashed so a changed
/// preview sentence (e.g. after a translation update) misses the cache
/// instead of playing the old wording.
pub async fn cached_sample_path(app: &AppHandle, voice: &str, text: &str) -> Option<PathBuf> {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let dir = managed_dir(app)?;
    let mut hasher = DefaultHasher::new();
    voice.hash(&mut hasher);
    text.hash(&mut hasher);
    let key = format!("{:016x}", hasher.finish());
    Some(samples_dir(&dir).join(format!("{}.wav", key)))
}

/// Synthesize `text` to `out` (wav). `voice` is either `preset:<name>` or
/// `profile:<id>` (a cloned voice).
pub async fn synthesize_vieneu(
    app: &AppHandle,
    text: &str,
    voice: &str,
    out: &Path,
) -> Result<(), String> {
    let out_str = out.to_string_lossy().to_string();
    let payload = if let Some(id) = voice.strip_prefix("lora:") {
        serde_json::json!({
            "op": "tts",
            "text": text,
            "lora": id,
            "out": out_str,
        })
    } else if let Some(id) = voice.strip_prefix("profile:") {
        let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
        let profiles = load_profiles(&dir).await;
        let profile = profiles
            .iter()
            .find(|p| p.id == id)
            .ok_or_else(|| format!("Cloned voice not found: {}", id))?;
        if !Path::new(&profile.file).exists() {
            return Err(format!("Reference audio missing for voice '{}'", profile.name));
        }
        serde_json::json!({
            "op": "tts",
            "text": text,
            "ref_audio": profile.file,
            // Bundled references are clean studio recordings; denoising them
            // just adds seconds to the one-time voice registration.
            "denoise": !profile.builtin,
            "style": profile.style.clone().unwrap_or_else(|| "tu_nhien".to_string()),
            "out": out_str,
        })
    } else {
        let name = voice.strip_prefix("preset:").unwrap_or(voice);
        serde_json::json!({
            "op": "tts",
            "text": text,
            "voice": name,
            "out": out_str,
        })
    };

    // The torch engine may download its base model on first use — give that
    // first request real headroom (synthesis itself is only a few seconds).
    let timeout = if voice.starts_with("lora:") {
        1800
    } else {
        REQUEST_TIMEOUT_SECS
    };
    let resp = worker_request(app, payload, timeout).await?;
    if resp.get("ok").and_then(|v| v.as_bool()) == Some(true) {
        Ok(())
    } else {
        let msg = resp
            .get("error")
            .and_then(|e| e.as_str())
            .unwrap_or("Local TTS synthesis failed")
            .to_string();
        // A missing-module error means the worker's Python env changed under
        // it (e.g. a dependency was installed after spawn) and the library
        // has cached the failed import — retries in this process can never
        // succeed. Drop the worker so the next request starts a fresh one.
        if msg.contains("No module named") {
            shutdown_worker().await;
        }
        Err(msg)
    }
}

async fn load_profiles(dir: &Path) -> Vec<VoiceProfile> {
    match tokio::fs::read_to_string(profiles_path(dir)).await {
        Ok(content) => serde_json::from_str(&content).unwrap_or_default(),
        Err(_) => Vec::new(),
    }
}

async fn save_profiles(dir: &Path, profiles: &[VoiceProfile]) -> Result<(), String> {
    tokio::fs::create_dir_all(voices_dir(dir))
        .await
        .map_err(|e| format!("Failed to create voices dir: {}", e))?;
    let json = serde_json::to_string_pretty(profiles).map_err(|e| e.to_string())?;
    tokio::fs::write(profiles_path(dir), json)
        .await
        .map_err(|e| format!("Failed to save voice profiles: {}", e))
}

/// Preset voice names, cached on disk after the first successful listing.
///
/// The names live inside the engine, so asking for them means booting the
/// worker and loading the model (~2-3s). That made every app start show a
/// spinner over the voice list even though the names never change between
/// releases — so remember them and serve subsequent starts instantly.
fn presets_cache_path(dir: &Path) -> PathBuf {
    dir.join("presets-cache.json")
}

async fn load_cached_presets(dir: &Path) -> Option<Vec<PresetVoice>> {
    let raw = tokio::fs::read_to_string(presets_cache_path(dir)).await.ok()?;
    let list: Vec<PresetVoice> = serde_json::from_str(&raw).ok()?;
    (!list.is_empty()).then_some(list)
}

/// Preset voices (from the SDK) + cloned profiles. Starts the worker if it
/// isn't running (cheap once the model is warm; the panel calls this when the
/// user switches to the local engine).
pub async fn list_vieneu_voices(app: &AppHandle) -> Result<LocalTtsVoices, String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    // Covers machines that installed the engine before a bundled voice was
    // added — an app update seeds it on the next listing.
    if dir.join(".installed").exists() {
        seed_bundled_voices(&dir).await;
    }
    let profiles = load_profiles(&dir).await;

    // Serve the remembered preset names when we have them: the list is
    // identical every run, so there is no reason to make the user wait for the
    // model to load just to see it.
    if let Some(presets) = load_cached_presets(&dir).await {
        let loras = LORA_VOICE_LIST
            .iter()
            .map(|(id, label)| PresetVoice {
                id: (*id).to_string(),
                label: (*label).to_string(),
            })
            .collect();
        return Ok(LocalTtsVoices {
            presets,
            profiles,
            loras,
        });
    }

    let resp = worker_request(app, serde_json::json!({"op": "voices"}), REQUEST_TIMEOUT_SECS).await?;
    let presets: Vec<PresetVoice> = resp
        .get("voices")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| {
                    let id = v.get("id").and_then(|i| i.as_str())?.to_string();
                    let label = v
                        .get("label")
                        .and_then(|l| l.as_str())
                        .unwrap_or(&id)
                        .to_string();
                    Some(PresetVoice { id, label })
                })
                .collect()
        })
        .unwrap_or_default();

    // Remember for next launch (best-effort — a failed write just means the
    // next start asks the engine again).
    if !presets.is_empty() {
        if let Ok(json) = serde_json::to_string_pretty(&presets) {
            let _ = tokio::fs::write(presets_cache_path(&dir), json).await;
        }
    }

    let loras = LORA_VOICE_LIST
        .iter()
        .map(|(id, label)| PresetVoice {
            id: (*id).to_string(),
            label: (*label).to_string(),
        })
        .collect();

    Ok(LocalTtsVoices {
        presets,
        profiles,
        loras,
    })
}

/// Register a cloned voice: convert the user's audio to a clean mono wav via
/// ffmpeg (any input format), store it under voices/, and persist the profile.
pub async fn add_vieneu_voice(
    app: &AppHandle,
    name: &str,
    source_path: &str,
    ffmpeg: &Path,
) -> Result<VoiceProfile, String> {
    let name = name.trim();
    if name.is_empty() {
        return Err("Voice name is empty".to_string());
    }
    if !Path::new(source_path).exists() {
        return Err(format!("Audio file not found: {}", source_path));
    }
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    tokio::fs::create_dir_all(voices_dir(&dir))
        .await
        .map_err(|e| format!("Failed to create voices dir: {}", e))?;

    let id = uuid::Uuid::new_v4().to_string();
    let dest = voices_dir(&dir).join(format!("{}.wav", id));
    let dest_str = dest.to_string_lossy().to_string();

    // Mono 48kHz wav, capped at 30s — VieNeu needs only 3-10s of reference,
    // and a long file just slows every synthesis down.
    let mut cmd = Command::new(ffmpeg);
    cmd.args([
        "-y",
        "-i",
        source_path,
        "-t",
        "30",
        "-ac",
        "1",
        "-ar",
        "48000",
        &dest_str,
    ]);
    cmd.hide_window();
    let out = cmd
        .output()
        .await
        .map_err(|e| format!("Failed to run ffmpeg: {}", e))?;
    if !out.status.success() {
        return Err(format!(
            "Audio conversion failed: {}",
            String::from_utf8_lossy(&out.stderr)
                .lines()
                .last()
                .unwrap_or("unknown error")
        ));
    }

    let profile = VoiceProfile {
        id,
        name: name.to_string(),
        file: dest_str,
        created_at: chrono::Utc::now().to_rfc3339(),
        builtin: false,
        style: None,
    };
    let mut profiles = load_profiles(&dir).await;
    profiles.push(profile.clone());
    save_profiles(&dir, &profiles).await?;
    Ok(profile)
}

pub async fn delete_vieneu_voice(app: &AppHandle, id: &str) -> Result<(), String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    let mut profiles = load_profiles(&dir).await;
    let Some(pos) = profiles.iter().position(|p| p.id == id) else {
        return Ok(());
    };
    let removed = profiles.remove(pos);
    let _ = tokio::fs::remove_file(&removed.file).await;
    // Sample filenames are hashes of voice+text, so there is no cheap way to
    // target just this voice's entries — and the cache is small and cheap to
    // rebuild, so drop it wholesale.
    let _ = tokio::fs::remove_dir_all(samples_dir(&dir)).await;
    save_profiles(&dir, &profiles).await
}

// ── engine settings ────────────────────────────────────────────────────────

/// Runtime knobs for the synthesis engine, persisted next to the install and
/// read by the worker at start-up.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTtsEngineConfig {
    /// "int8" (fast, default) or "fp32" (closer voice match, ~15% slower).
    pub precision: String,
}

impl Default for LocalTtsEngineConfig {
    fn default() -> Self {
        Self {
            precision: "int8".to_string(),
        }
    }
}

fn engine_config_path(dir: &Path) -> PathBuf {
    dir.join("engine.json")
}

pub async fn get_engine_config(app: &AppHandle) -> LocalTtsEngineConfig {
    let Some(dir) = managed_dir(app) else {
        return LocalTtsEngineConfig::default();
    };
    match tokio::fs::read_to_string(engine_config_path(&dir)).await {
        Ok(raw) => serde_json::from_str(&raw).unwrap_or_default(),
        Err(_) => LocalTtsEngineConfig::default(),
    }
}

/// Persist engine settings and drop the worker so the next request picks them
/// up (precision is chosen when the model is loaded, not per request).
pub async fn set_engine_config(
    app: &AppHandle,
    config: &LocalTtsEngineConfig,
) -> Result<(), String> {
    let precision = match config.precision.to_lowercase().as_str() {
        "fp32" => "fp32",
        _ => "int8",
    };
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    tokio::fs::create_dir_all(&dir)
        .await
        .map_err(|e| format!("Failed to create vieneu dir: {}", e))?;
    let json = serde_json::to_string_pretty(&LocalTtsEngineConfig {
        precision: precision.to_string(),
    })
    .map_err(|e| e.to_string())?;
    tokio::fs::write(engine_config_path(&dir), json)
        .await
        .map_err(|e| format!("Failed to save engine config: {}", e))?;
    // Samples were rendered by the previous graph — they no longer match.
    let _ = tokio::fs::remove_dir_all(samples_dir(&dir)).await;
    shutdown_worker().await;
    Ok(())
}

// ── bundled voices ─────────────────────────────────────────────────────────

/// Voice profiles shipped inside the binary and seeded on install: (stable id,
/// display name, reference wav). INTERNAL BUILDS ONLY for the current entry —
/// the Ngọc Huyền reference is CC-BY-NC (see resources/voices/*_LICENSE.txt);
/// remove it before any public/commercial release.
/// (id, display name, reference wav, reading style)
const BUNDLED_VOICES: &[(&str, &str, &[u8], &str)] = &[(
    "bundled-ngoc-huyen",
    "Ngọc Huyền",
    include_bytes!("../../resources/voices/ngoc_huyen.wav"),
    // The reference is a news broadcast; "tin_tuc" matches its delivery.
    "tin_tuc",
)];

/// Seed bundled voice profiles once per machine. A marker per voice id (not
/// the profile's presence) gates re-seeding, so a user who deletes a bundled
/// voice doesn't get it forced back on the next launch.
async fn seed_bundled_voices(dir: &Path) {
    for (id, name, bytes, style) in BUNDLED_VOICES {
        let marker = voices_dir(dir).join(format!(".seeded-{}", id));
        if marker.exists() {
            continue;
        }
        if tokio::fs::create_dir_all(voices_dir(dir)).await.is_err() {
            return;
        }
        let wav_path = voices_dir(dir).join(format!("{}.wav", id));
        if tokio::fs::write(&wav_path, bytes).await.is_err() {
            continue;
        }
        let mut profiles = load_profiles(dir).await;
        if !profiles.iter().any(|p| p.id == *id) {
            profiles.push(VoiceProfile {
                id: (*id).to_string(),
                name: (*name).to_string(),
                file: wav_path.to_string_lossy().to_string(),
                created_at: chrono::Utc::now().to_rfc3339(),
                builtin: true,
                style: Some((*style).to_string()),
            });
            if save_profiles(dir, &profiles).await.is_err() {
                continue;
            }
        }
        let _ = tokio::fs::write(&marker, "ok").await;
    }
}

// ── generation history (audios created in the TTS studio) ─────────────────

/// One audio created in the Voices page studio. Dub clips from the editor are
/// deliberately NOT recorded here — a single video produces hundreds of them.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TtsGeneration {
    pub id: String,
    /// The synthesized text (truncated for display).
    pub text: String,
    /// Display label of the voice used.
    pub voice_label: String,
    /// Absolute path of the wav in the app's tts output dir.
    pub path: String,
    pub duration_ms: i64,
    pub created_at: String,
}

/// Newest-first cap; the wav of an entry that falls off is deleted with it.
const MAX_GENERATIONS: usize = 100;

fn generations_path(dir: &Path) -> PathBuf {
    dir.join("generations.json")
}

async fn load_generations(dir: &Path) -> Vec<TtsGeneration> {
    match tokio::fs::read_to_string(generations_path(dir)).await {
        Ok(content) => serde_json::from_str(&content).unwrap_or_default(),
        Err(_) => Vec::new(),
    }
}

async fn save_generations(dir: &Path, items: &[TtsGeneration]) -> Result<(), String> {
    let json = serde_json::to_string_pretty(items).map_err(|e| e.to_string())?;
    tokio::fs::write(generations_path(dir), json)
        .await
        .map_err(|e| format!("Failed to save generation history: {}", e))
}

pub async fn record_vieneu_generation(
    app: &AppHandle,
    text: &str,
    voice_label: &str,
    path: &str,
    duration_ms: i64,
) -> Result<TtsGeneration, String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    tokio::fs::create_dir_all(&dir)
        .await
        .map_err(|e| format!("Failed to create vieneu dir: {}", e))?;

    let entry = TtsGeneration {
        id: uuid::Uuid::new_v4().to_string(),
        text: text.chars().take(200).collect(),
        voice_label: voice_label.to_string(),
        path: path.to_string(),
        duration_ms,
        created_at: chrono::Utc::now().to_rfc3339(),
    };
    let mut items = load_generations(&dir).await;
    items.insert(0, entry.clone());
    while items.len() > MAX_GENERATIONS {
        if let Some(dropped) = items.pop() {
            let _ = tokio::fs::remove_file(&dropped.path).await;
        }
    }
    save_generations(&dir, &items).await?;
    Ok(entry)
}

/// List history, silently pruning entries whose wav was deleted out-of-band.
pub async fn list_vieneu_generations(app: &AppHandle) -> Vec<TtsGeneration> {
    let Some(dir) = managed_dir(app) else {
        return Vec::new();
    };
    let items = load_generations(&dir).await;
    let kept: Vec<TtsGeneration> = items
        .iter()
        .filter(|g| Path::new(&g.path).exists())
        .cloned()
        .collect();
    if kept.len() != items.len() {
        let _ = save_generations(&dir, &kept).await;
    }
    kept
}

pub async fn delete_vieneu_generation(app: &AppHandle, id: &str) -> Result<(), String> {
    let dir = managed_dir(app).ok_or("Failed to resolve app data dir")?;
    let mut items = load_generations(&dir).await;
    let Some(pos) = items.iter().position(|g| g.id == id) else {
        return Ok(());
    };
    let removed = items.remove(pos);
    let _ = tokio::fs::remove_file(&removed.path).await;
    save_generations(&dir, &items).await
}

// ── storage accounting (Settings → Storage & Models) ──────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct LocalTtsStorage {
    pub installed: bool,
    /// Voice model cache (.hf) — safe to clear; re-downloads on next use.
    pub models_bytes: u64,
    /// Cloned voice references (voices/) — removed only by uninstall.
    pub voices_bytes: u64,
    /// Everything else (venv, bundled Python) — removed only by uninstall.
    pub runtime_bytes: u64,
    pub total_bytes: u64,
}

/// Sum the sizes of all files under `path` (recursive). Blocking; callers run
/// it on a blocking thread.
fn dir_size(path: &Path) -> u64 {
    let mut total = 0u64;
    let Ok(entries) = std::fs::read_dir(path) else {
        return 0;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let Ok(meta) = entry.metadata() else { continue };
        if meta.is_dir() {
            total += dir_size(&entry.path());
        } else {
            total += meta.len();
        }
    }
    total
}

pub async fn vieneu_storage_internal(app: &AppHandle) -> LocalTtsStorage {
    let empty = LocalTtsStorage {
        installed: false,
        models_bytes: 0,
        voices_bytes: 0,
        runtime_bytes: 0,
        total_bytes: 0,
    };
    let Some(dir) = managed_dir(app) else {
        return empty;
    };
    let installed = dir.join(".installed").exists();
    if !dir.exists() {
        return empty;
    }

    let dir_clone = dir.clone();
    let (models, voices, total) = tokio::task::spawn_blocking(move || {
        let hf = dir_clone.join(".hf");
        let voices_dir = dir_clone.join("voices");
        (
            if hf.exists() { dir_size(&hf) } else { 0 },
            if voices_dir.exists() { dir_size(&voices_dir) } else { 0 },
            dir_size(&dir_clone),
        )
    })
    .await
    .unwrap_or((0, 0, 0));

    LocalTtsStorage {
        installed,
        models_bytes: models,
        voices_bytes: voices,
        runtime_bytes: total.saturating_sub(models).saturating_sub(voices),
        total_bytes: total,
    }
}

/// Delete the voice-model cache (.hf) without touching the install or the
/// cloned voices. Models re-download on the next synthesis. Returns bytes
/// reclaimed.
pub async fn clean_vieneu_models_internal(app: &AppHandle) -> Result<u64, String> {
    // The worker holds the models open (and would re-create cache files);
    // stop it first so the next request re-downloads cleanly.
    shutdown_worker().await;
    let Some(dir) = managed_dir(app) else {
        return Ok(0);
    };
    let hf = dir.join(".hf");
    if !hf.exists() {
        return Ok(0);
    }
    let freed = {
        let hf = hf.clone();
        tokio::task::spawn_blocking(move || dir_size(&hf))
            .await
            .unwrap_or(0)
    };
    tokio::fs::remove_dir_all(&hf)
        .await
        .map_err(|e| format!("Failed to clear model cache: {}", e))?;
    Ok(freed)
}
